[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"
  NODE_ENV = "10.15.3"

[[redirects]]
  from = "/financial-education-mapping-tool"
  to = "https://knology.shinyapps.io/knologyfinedstatespendingshiny/"
[[redirects]]
  from = "/Financial-Education-Mapping-Tool"
  to = "https://knology.shinyapps.io/knologyfinedstatespendingshiny/"

## Redirects resulting in change from "wellness" to "wellbeing" 
[[redirects]]
  from = "/category/wellness"
  to = "/category/wellbeing"
[[redirects]]
  from = "/articles/category/wellness"
  to = "/articles/category/wellbeing"
[[redirects]]
  from = "/initiative/understanding-health-narratives"
  to = "/initiative/social-construction-of-public-health-and-wellbeing"
[[redirects]]
  from = "/initiative/mindfulness"
  to = "/category/wellbeing"
[[redirects]]
  from = "/initiative/pre-arming-self-efficacy-capacity-building"
  to = "/initiative/social-life-of-public-health-disasters"

## Redirects because a previously published article was removed
[[redirects]]
  from = "/article/financial-education-database-training-fellowship-application"
  to = "/article/2022-nefe-knology-fellowship"
[[redirects]]
  from = "/article/can-the-news-help-you-learn-statistics"
  to = "/article/meaningful-math"